unstable_features = true
edition = "2021"

imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
max_width = 115
use_small_heuristics = "max"
